# Generated by Django 6.0.1 on 2026-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annonces', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='licence',
            field=models.CharField(blank=True, choices=[('ALL', 'Toutes les Licences (Tout le campus)'), ('L1', 'Licence 1 (L1)'), ('L2', 'Licence 2 (L2)'), ('L3', 'Licence 3 (L3)')], default='ALL', help_text='Choisissez la Licence concernée par cette information (ou Toutes les Licences pour tout le campus).', max_length=10, verbose_name='Licence concernée'),
        ),
    ]
