# Generated by Django 6.0.1 on 2026-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/attachments/', verbose_name='Sujet / Pièce jointe'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_points',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Note maximale'),
        ),
    ]
