# Generated by Django 6.0.1 on 2026-10-07 10:53

import Codex.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0002_assignment_attachment_assignment_max_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/attachments/', validators=[Codex.validators.validate_secure_file_extension, Codex.validators.validate_file_size], verbose_name='Sujet / Pièce jointe'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to='assignments/submissions/', validators=[Codex.validators.validate_secure_file_extension, Codex.validators.validate_file_size]),
        ),
    ]
