# Generated by Django 6.0.1 on 2026-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, default='Informatique', max_length=100, verbose_name='Filière / Catégorie'),
        ),
    ]
