# Generated by Django 6.0.1 on 2026-10-07 10:53

import Codex.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0002_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='licence',
            field=models.CharField(choices=[('ALL', 'Toutes les Licences'), ('L1', 'Licence 1 (L1)'), ('L2', 'Licence 2 (L2)'), ('L3', 'Licence 3 (L3)')], default='ALL', max_length=10, verbose_name='Niveau / Licence requis'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file',
            field=models.FileField(upload_to='courses/resources/', validators=[Codex.validators.validate_secure_file_extension, Codex.validators.validate_file_size]),
        ),
    ]
