# Generated by Django 6.0.1 on 2026-10-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0003_course_licence_alter_courseresource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='licence',
            field=models.CharField(blank=True, choices=[('ALL', 'Toutes les Licences'), ('L1', 'Licence 1 (L1)'), ('L2', 'Licence 2 (L2)'), ('L3', 'Licence 3 (L3)')], default='ALL', max_length=10, verbose_name='Niveau / Licence requis'),
        ),
    ]
