# Generated by Django 6.0.1 on 2026-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='user',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Filière / Département'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=True),
        ),
    ]
