# Generated by Django 6.0.1 on 2026-10-07 10:53

import Codex.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='licence',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1 (L1)'), ('L2', 'Licence 2 (L2)'), ('L3', 'Licence 3 (L3)')], max_length=10, null=True, verbose_name='Niveau / Licence'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/', validators=[Codex.validators.validate_avatar_image, Codex.validators.validate_file_size]),
        ),
    ]
