# Generated by Django 6.0.1 on 2026-10-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes', '0004_user_licence_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Avatar permanent (Base64)'),
        ),
    ]
