"""
Django settings for Codex project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file if present
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY: Secret key management with production enforcement
_secret_key = os.environ.get('SECRET_KEY')
_debug_env = os.environ.get('DEBUG', 'False').lower() in ['true', '1', 'yes']

if not _secret_key:
    # Fallback sécurisé généré si non défini dans les variables d'environnement
    _secret_key = 'django-insecure-coolify-prod-key-f9x7k2p8z1m4v6b3c5a8e0d'

SECRET_KEY = _secret_key
DEBUG = _debug_env

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', '*').split(',') if host.strip()]

raw_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in raw_csrf.split(',') if o.strip()]
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = ['https://codex.sacko-tech.com', 'http://127.0.0.1:8000', 'http://localhost:8000']

# Derrière le reverse proxy (Traefik / Nginx / Coolify)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# URL d'administration non devinable (ex: ADMIN_URL=gestion-x7k2p9/)
ADMIN_URL = os.environ.get('ADMIN_URL', 'admin/').lstrip('/')
if ADMIN_URL and not ADMIN_URL.endswith('/'):
    ADMIN_URL += '/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Comptes',
    'Cours',
    'Missions',
    'Annonces',
    'Forum',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'Codex.middleware.SecurityHeadersMiddleware',
    'Codex.middleware.LoginRateLimitMiddleware',
    'Codex.middleware.AntiReverseEngineeringMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Codex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Comptes.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Codex.wsgi.application'


# Database Configuration
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# PostgreSQL is the primary database for Codex. Supports DATABASE_URL or individual variables.
import dj_database_url

DATABASE_URL = os.environ.get('DATABASE_URL')
# Utiliser PostgreSQL si une URL est fournie, ou si un hôte/moteur est spécifié, ou si activé par variable
USE_POSTGRES = bool(DATABASE_URL) or (
    os.environ.get('USE_POSTGRESQL', '').lower() in ['true', '1', 'yes'] or
    bool(os.environ.get('POSTGRES_HOST')) or
    os.environ.get('DB_ENGINE', '').lower() == 'postgresql'
)

ROOT_DB = BASE_DIR / 'db.sqlite3'
DATA_DIR = BASE_DIR / 'data'
DATA_DB = DATA_DIR / 'db.sqlite3'

# Prioriser la base de données existante avec toutes ses tables
if ROOT_DB.exists() and ROOT_DB.stat().st_size > 0:
    SQLITE_PATH = ROOT_DB
elif DATA_DB.exists() and DATA_DB.stat().st_size > 0:
    SQLITE_PATH = DATA_DB
elif DATA_DIR.exists() and os.access(DATA_DIR, os.W_OK):
    SQLITE_PATH = DATA_DB
else:
    SQLITE_PATH = ROOT_DB

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB') or os.environ.get('UNIVERSITY_DB_NAME') or 'university_db',
            'USER': os.environ.get('POSTGRES_USER') or os.environ.get('DB_USER') or 'postgres',
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD') or os.environ.get('DB_PASSWORD') or 'postgres',
            'HOST': os.environ.get('POSTGRES_HOST') or os.environ.get('DB_HOST') or 'localhost',
            'PORT': os.environ.get('POSTGRES_PORT') or os.environ.get('DB_PORT') or '5432',
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                'client_encoding': 'UTF8',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': SQLITE_PATH,
        }
    }


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'codex_security_cache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Email Backend Configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'Comptes.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

# Security & Anti-Hacking Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

# Session & Cookie Security
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 86400  # Auto-expire sessions after 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Production SSL Security (Derrière Coolify/Traefik le SSL est géré par le proxy)
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() in ['true', '1', 'yes']
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year HSTS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Protection DoS sur les téléversements
DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25 Mo
FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25 Mo
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Durcissement supplémentaire
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SESSION_COOKIE_NAME = 'cx_sid'
CSRF_COOKIE_NAME = 'cx_csrf'

# Journalisation détaillée pour le diagnostic des erreurs 500 sur Coolify
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} [{name}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
